//audio to variables.
let CChord = document.getElementById("audio1");
let GChord = document.getElementById("audio2");
let AmChord = document.getElementById("audio3");
let FChord = document.getElementById("audio4");
let CBass = document.getElementById("audio5");
let GBass = document.getElementById("audio6");
let ABass = document.getElementById("audio7");
let FBass = document.getElementById("audio8");
let CO1Note = document.getElementById("audio9");
let DO1Note = document.getElementById("audio10");
let EO1Note = document.getElementById("audio11");
let FO1Note = document.getElementById("audio12");
let GO1Note = document.getElementById("audio13");
let AO1Note = document.getElementById("audio14");
let BO1Note = document.getElementById("audio15");
let CO2Note = document.getElementById("audio16");
let DO2Note = document.getElementById("audio17");
let EO2Note = document.getElementById("audio18");
let FO2Note = document.getElementById("audio19");
let GO2Note = document.getElementById("audio20");
let AO2Note = document.getElementById("audio21");
let BO2Note = document.getElementById("audio22");
let CO3Note = document.getElementById("audio23");
let DO3Note = document.getElementById("audio24");
let EO3Note = document.getElementById("audio25");
let FO3Note = document.getElementById("audio26");
let GO3Note = document.getElementById("audio27");
let AO3Note = document.getElementById("audio28");
let BO3Note = document.getElementById("audio29");
let CO4Note = document.getElementById("audio30");
let DO4Note = document.getElementById("audio31");
let EO4Note = document.getElementById("audio32");
let FO4Note = document.getElementById("audio33");
let GO4Note = document.getElementById("audio34");
let AO4Note = document.getElementById("audio35");
let BO4Note = document.getElementById("audio36");
let drumBass = document.getElementById("audio37");
let snare = document.getElementById("audio38");
let hat = document.getElementById("audio39");
let crash = document.getElementById("audio40");



function setVolume() {
    let drumBassvolume = 0.15,
        hatVolume = 0.1,
        crashVolume = 0.5,
        chordVolume = 0.4,
        noteVolume = 0.6,
        bassVolume = 0.4;
    drumBass.volume = drumBassvolume;
    CBass.volume = bassVolume;
    GBass.volume = bassVolume;
    ABass.volume = bassVolume;
    FBass.volume = bassVolume;
    hat.volume = hatVolume;
    crash.volume = crashVolume;
    CChord.volume = chordVolume;
    GChord.volume = chordVolume;
    AmChord.volume = chordVolume;
    FChord.volume = chordVolume;

    CO1Note.volume = noteVolume;
    DO1Note.volume = noteVolume;
    EO1Note.volume = noteVolume;
    FO1Note.volume = noteVolume;
    GO1Note.volume = noteVolume;
    AO1Note.volume = noteVolume;
    BO1Note.volume = noteVolume;
    CO2Note.volume = noteVolume;
    DO2Note.volume = noteVolume;
    EO2Note.volume = noteVolume;
    FO2Note.volume = noteVolume;
    GO2Note.volume = noteVolume;
    AO2Note.volume = noteVolume;
    BO2Note.volume = noteVolume;
    CO3Note.volume = noteVolume;
    DO3Note.volume = noteVolume;
    EO3Note.volume = noteVolume;
    FO3Note.volume = noteVolume;
    GO3Note.volume = noteVolume;
    AO3Note.volume = noteVolume;
    BO3Note.volume = noteVolume;
    CO4Note.volume = noteVolume;
    DO4Note.volume = noteVolume;
    EO4Note.volume = noteVolume;
    FO4Note.volume = noteVolume;
    GO4Note.volume = noteVolume;
    AO4Note.volume = noteVolume;
    BO4Note.volume = noteVolume;
}